services:
  db:
    image: postgres:15-alpine
    container_name: sga_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "Password123!"
      POSTGRES_DB: SGA_Avicola
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./SGA
      dockerfile: Dockerfile
    container_name: sga_api
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=SGA_Avicola;Username=postgres;Password=Password123!
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data:
