services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sga_db_dev
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password123!"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data_dev:/var/opt/mssql

volumes:
  mssql_data_dev:
